



name: Update README

on:
  schedule:
    - cron: "50 * * * *"

jobs:
  run-interface:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install Dependencies if not cached
      if: steps.cache-pip-dependencies.outputs.cache-hit != 'true'
      run: |-
          pip install -r nekos
      
    - name: Run Python interface
      run: python main.py
